name: Build and Push Dockerhub
on:
  push:
    branches: [master]
    paths-ignore:
      - .github/**
      - README.md
  release:
    types: [published]
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: andy008/scan-index
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Dockerhub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
      - name: Image digest
        run: "echo Image Digest: ${{ steps.docker_build.outputs.digest }}"
      - name: Image Tag
        run: "echo 'Image Tags: ${{ steps.docker_meta.outputs.tags }}'"